project:
  type: "book"
  output-dir: docs
 
book: 
  title: "Core Mathematics III"
  author: "Prof Gunnar Hornig"
  # css: "assets/style.css"
  description: |
     Notes for MA21001.
  site-url: https://dundeemath.github.io/MA21001
  repo-url: https://github.com/dundeemath/MA21001/
  repo-branch: master
  #cover-image: cover.png
  #cover-image-alt: "Cover for lecture note packet."
  downloads: pdf
  repo-actions: [issue]
  # sharing: [twitter]
  date: last-modified
  date-format: iso
  page-footer: "Copyright 2025, Gunnar Hornig (University of Dundee)"  
  page-navigation: true
  search: true
  # collapse-level: 1
  chapters: 
    - "index.qmd"
    - part: "Algebra"
      chapters:
        - "notation.qmd"
        - "algebra3b.qmd"
        - "linearequations.qmd"
        - "determinants.qmd"
        - "eigenvalues.qmd"
        - "appendix.qmd"
        # - "09-references.qmd"

  # appendices: 
  # margin-header: "Header Text"
  sidebar:
    alignment: left
    logo: 'assets/images/uod_shield_rgb.png'
    logo-alt: 'University of Dundee shield'
    # footer: |
    #   Last modified: {{< meta date >}}

# bibliography:
#  - MA21002.bib

prefer-html: true
  
format: 
  html: 
    theme: 
      light: flatly
      dark: darkly
      # - assets/style.css
    # css: assets/mermaid-bootstrap.css
    code-tools: true
    code-background: true
    code-fold: show
    code-copy: true
    code-overflow: wrap
    toc: true
    html-math-method: katex
    include-in-header: header.qmd
  pdf: 
    code-overflow: wrap
    documentclass: scrreprt
    papersize: a4
    include-in-header: preamble.tex
    classoption: oneside
    keep-tex: true
    pdf-engine: xelatex
    citation_method: natbib
    link-citations: true
    link-bibliography: true
    cover-image: assets/images/cover_small.jpg
    mermaid:
      mermaid-format: svg
      theme: neutral
      themeVariables:
        fontSize: "10px"
    
execute: 
  freeze: auto

filters:
  - custom-numbered-blocks

custom-numbered-blocks:
  groups:
    thmlike:
      colors: [948bde, 584eab]
      boxstyle: foldbox.simple
      collapse: false
      listin: [mathstuff]
    todos: default  
  classes:
    Theorem:
      group: thmlike
    Corollary:
      group: thmlike
    Lemma:
      group: thmlike
    Conjecture:
      group: thmlike
      collapse: true  
    Proof:
      group: todos
      collapse: true  
      numbered: false
    Solution:
      group: todos
      collapse: true  
      numbered: false
    Definition:
      group: thmlike
      colors: [d999d3, a01793]
    Feature: default
    TODO:
      label: "To do"
      colors: [e7b1b4, 8c3236]
      group: todos
      listin: [stilltodo]
    DONE:
      label: "Done"
      colors: [cce7b1, 86b754]  
      group: todos

     # crossref:
     #   chapters: true
     #  eq-title: Eq -->
    