# Determinants

## Introduction

<!--See Poole: Linear Algebra, *A Modern Introduction*, pages 256--285.-->

Determinants occur in many situations, geometrically they can beinterpreted as the volume of the parallelepiped spanned by a set of $n$ vectors. This is easily visualised in two dimensions (x-y-plane). The area (2-dimensional volume) of a parallelepiped spanned by the two vectors
${\bf b}=(b_{1},b_{2})^{T}$ and ${\bf c}=(c_{1},c_{2})^{t}$ is up to a
sign given by 
$$area = \pm(b_{1}c_{2}- b_{2} c_{1} )$$ 
We call this the determinant of the matrix ${\rm A} = [{\bf b},{\bf c}]$ and write
$${\rm det(A)}= |{\rm A}|=\left| 
\begin{array}{cc}
b_{1} & c_{1} \\ 
b_{2} & c_{2}
\end{array}
\right| = b_{1}c_{2}- b_{2} c_{1} .$$ 
The determinant of a square matrix
$A$, denoted by $\det$($A$), or $\left|
A\right|$, is a number (scalar). The now-standard notation was first
introduced by Cayley in 1841.

In three dimensions, the volume of the cell spanned by the vectors
${\bf a}$, ${\bf b}$, and ${\bf c}$ is given by
$${\bf a}\cdot ( {\bf b} \times {\bf c} )= a_{1}(b_{2}c_{3}- b_{3}c_{2}) + a_{2} (b_{3}c_{1}-b_{1}c_{3}) + a_{3} (b_{1}c_{2}-b_{2}c_{1}).$$
Note that we can write this in terms of the determinants of 2x2
matrices: $${\bf a}\cdot ({\bf b} \times {\bf c}) = \left| 
\begin{array}{ccc}
a_{1} & b_{1} & c_{1} \\ 
a_{2} & b_{2} & c_{2} \\ 
a_{3} & b_{3} & c_{3}
\end{array}
\right|  = a_{1} \left| 
\begin{array}{cc}
b_{2} & c_{2} \\ 
b_{3} & c_{3}
\end{array}
\right|  - a_{2} \left| 
\begin{array}{cc}
b_{1} & c_{1} \\ 
b_{3} & c_{3}
\end{array}
\right| + a_{3} \left| 
\begin{array}{cc}
b_{1} & c_{1} \\ 
b_{2} & c_{2}
\end{array}
\right| ,$$ where each of the $2 \times 2$ matrices is obtained by
deleting the first column and the corresponding row of the coefficient
$a_{j}$ from the matrix ${\rm A} = [{\bf a},{\bf b}, {\bf c}]$. This
suggests a recursive scheme where determinants of arbitrary $n \times n$
matrices are defined in terms of determinants of $(n-1)\times(n-1)$
matrices, which again are expanded in determinants of $(n-2)\times(n-2)$
and so on.

::: {#exm-det1}
Evaluate 
$$\left| 
\begin{array}{ccc}
1 & 2 & 3 \\ 
2 & 3 & 2 \\ 
3 & 3 & 4
\end{array}
\right| .$$
:::

::: {.Definition}
# Minor and Cofactor
Corresponding to each entry $a_{i,j}$ in an $n\times n$ matrix $A,$ we define a number $M_{ij},$
called the *minor* of $a_{ij},$ which is the $\left( n-1\right)$th order
determinant obtained by deleting the $i$-th row and $j$-th column from
$A.$

The cofactor $C_{ij}$ corresponding to an entry $a_{ij}$ in an
$n\times n$ matrix $A$ is the product of its minor and the sign
$\left( -1\right) ^{i+j}:$ $C_{ij}=\left( -1\right) ^{i+j}M_{ij}.$ The
$n^{2}$ cofactors form a matrix of cofactors.
:::

::: {.Definition} 
## Determinants 
A determinant of an $n \times n$ matrix can be expanded in terms of $(n-1)\times(n-1)$ determinants using
either a column or a row. Expansion along the i-th column:
$$\left| A\right| =a_{1,i}C_{1,i}+a_{2,i}C_{2,i}+a_{3,i}C_{3,i}+\cdots
+a_{n,i}C_{n,i}.$$ Expansion along the i-th row:
$$\left| A\right| =a_{i,1}C_{i,1}+a_{i,2}C_{i,2}+a_{i,3}C_{i,3}+\cdots
+a_{i,n}C_{i,n}.$$ The $(n-1)\times(n-1)$ determinants can then be
recursively further reduced down to $2\times2$ matrices.
:::

::: {#exm-det3}
Find the expansion for the matrix $A$ of the previous Example. Expansion along the first
row: $$\left| 
\begin{array}{ccc}
1 & 2 & 3 \\ 
2 & 3 & 2 \\ 
3 & 3 & 4
\end{array}
\right| =  1  \left| \begin{array}{cc}
3 & 2 \\ 
 3 & 4
\end{array} \right| - 2  \left| \begin{array}{cc}
2 & 2 \\ 
3 & 4
\end{array}  \right| +3 \left| \begin{array}{cc}
2 & 3 \\ 
3 & 3
\end{array}  \right| =  6-4 -9 =-7$$ Expansion along the first column:
$$\left| 
\begin{array}{ccc}
1 & 2 & 3 \\ 
2 & 3 & 2 \\ 
3 & 3 & 4
\end{array}
\right| =  1  \left| \begin{array}{cc}
3 & 2 \\ 
 3 & 4
\end{array} \right| - 2  \left| \begin{array}{cc}
2 & 3 \\ 
3 & 4
\end{array}  \right| + 3\left| \begin{array}{cc}
2 & 3 \\ 
3 & 2
\end{array}  \right| =6+2-15=-7$$ Expansion along the second column:
$$\left| 
\begin{array}{ccc}
1 & 2 & 3 \\ 
2 & 3 & 2 \\ 
3 & 3 & 4
\end{array}
\right| =  - 2  \left| \begin{array}{cc}
2 & 2 \\ 
3 & 4
\end{array}  \right| +3 \left| \begin{array}{cc}
1 & 3 \\ 
3 & 4
\end{array}  \right| -3 \left| \begin{array}{cc}
1 & 3 \\ 
2 & 2
\end{array}  \right| =  -4 -15 +12=-7$$
:::

::: {#exm-det4}
Evaluate 
$$\begin{aligned}
\left| 
\begin{array}{cccc}
1 & 2 & 1 & 3 \\ 
1 & 1 & 2 & 1 \\ 
3 & 2 & 0 & 2 \\ 
2 & 2 & 1 & 0
\end{array}
\right| & = 1\left| 
\begin{array}{ccc} 
 1 & 2 & 1 \\ 
 2 & 0 & 2 \\ 
 2 & 1 & 0
\end{array}
\right| - 1 \left| 
\begin{array}{ccc}
 2 & 1 & 3 \\ 
 2 & 0 & 2 \\ 
 2 & 1 & 0
\end{array}
\right|  + 3 \left| 
\begin{array}{ccc}
 2 & 1 & 3 \\ 
 1 & 2 & 1 \\ 
 2 & 1 & 0
\end{array}
\right| - 2 \left| 
\begin{array}{ccc}
 2 & 1 & 3 \\ 
 1 & 2 & 1 \\ 
 2 & 0 & 2 \end{array}
\right| \\
& = 1\left| 
\begin{array}{cc} 
 0 & 2 \\ 
 1 & 0
\end{array}
\right| -2  \left|\begin{array}{cc} 
 2& 2 \\ 
 2 & 0
\end{array}
\right|  - ... \text{10 more terms} 
\end{aligned}$$
:::

The previous example should illustrate the large amount of computation
needed by using a "brute force" approach to evaluating determinants. We
will now look at smarter ways, using two fundamental theorems to develop
a simple numerical procedure closely related to Gaussian elimination.
The following example shows that it is much more efficient to calculate
determinants with many zeros in columns or rows:

::: {#exm-det5}
Evaluate 
$$\left| 
\begin{array}{cccc}
1 & 2 & 1 & 3 \\ 
0 & 1 & 1 & -2 \\ 
0 & 0 & 7 & -1 \\ 
0 & 0 & 3 & 2
\end{array}
\right| $$
:::
::: {.Solution}
Expanding along the first column, twice:
$$ \left| 
\begin{array}{cccc}
1 & 2 & 1 & 3 \\ 
0 & 1 & 1 & -2 \\ 
0 & 0 & 7 & -1 \\ 
0 & 0 & 3 & 2
\end{array}
\right| =\left| 
\begin{array}{ccc}
1 & 1 & -2 \\ 
0 & 7 & -1 \\ 
0 & 3 & 2
\end{array}
\right| =\left| 
\begin{array}{cc}
7 & -1 \\ 
3 & 2
\end{array}
\right| =\allowbreak 17.$$
:::

## Simplification of Determinants

The following rules help to simplify determinants efficiently:

::: {.Corollary #calcdet}
## Calculation of Determinants 

1.  If two rows (columns) of $A$ are interchanged to give a matrix $B$
    then $\left| B\right| =-\left| A\right|$.

2.  If two rows (columns) of $A$ are equal then $\left| A\right| =0$

3.  If all the entries in any row (column) of $A$ are multiplied by a
    scalar $k,$ the determinant is also multiplied by $k$

4.  If one row (column) of $A$ is a multiple of another row (column),
    then $\left|
    A\right| =0$

5.  If the matrix $B$ is obtained from $A$ by taking multiple of one
    row (column) and adding it to another row (column), then
    $\left| B\right|
    =\left| A\right| .$

6.  $\left| A\right| =\left| A^{T}\right| .$
:::

::: {.Proof}
The proof of (1) and (6) is omitted.\
(2) is proved by using (1): If we interchange the two equal columns of
${\rm A}$, then we obtain ${\rm A}$ again, hence $|{\rm A}|$ remains the
same, but according to (1) it should change its sign. This is only
possible if $|{\rm A}|=0.$

\(3\) If $B$ is obtained by multiplying the $i$th column of $A$ by $k:$
$$\left| A\right| =\left| 
\begin{array}{cccc}
a_{1} & b_{1} & c_{1} & \cdots \\ 
a_{2} & b_{2} & c_{2} &  \\ 
\vdots &  &  &  \\ 
a_{i} & b_{i} & c_{i} &  \\ 
\vdots &  &  & 
\end{array}
\right| ,\quad \left| B\right| =\left| 
\begin{array}{cccc}
a_{1} & b_{1} & c_{1} & \cdots \\ 
a_{2} & b_{2} & c_{2} &  \\ 
\vdots &  &  &  \\ 
ka_{i} & kb_{i} & kc_{i} &  \\ 
\vdots &  &  & 
\end{array}
\right|$$ and expand both determinants about their $i$th rows:
$$\begin{aligned}
\left| A\right| &=a_{i}C_{i,1}+b_{i}C_{i,2}+\cdots \\
\left| B\right| &=\left( ka_{i}\right) C_{i,1}+\left( kb_{i}\right)
C_{i,2}+\cdots \\
&=k\left( a_{i}C_{i,1}+b_{i}C_{i,2}+\cdots \right) =k\left| A\right| .
\end{aligned}$$ (4) We use (3) and (2).

\(5\) Suppose we add $k\times$ row $j$ to row $i$ of $\left|
A\right|$ to give $\left| B\right| :$ $$\left| A\right| =\left| 
\begin{array}{cccc}
a_{1} & b_{1} & c_{1} & \cdots \\ 
a_{2} & b_{2} & c_{2} &  \\ 
\vdots &  &  &  \\ 
a_{i} & b_{i} & c_{i} &  \\ 
\vdots &  &  & 
\end{array}
\right| ,\quad \left| B\right| =\left| 
\begin{array}{cccc}
a_{1} & b_{1} & c_{1} & \cdots \\ 
a_{2} & b_{2} & c_{2} &  \\ 
\vdots &  &  &  \\ 
a_{i}+ka_{j} & b_{i}+kb_{j} & c_{i}+kc_{j} &  \\ 
\vdots &  &  & 
\end{array}
\right|$$ and we now expand $\left| B\right|$ by its $i$th row
$$\begin{aligned}
\left| A\right| &=a_{i}C_{i,1}+b_{i}C_{i,2}+\cdots \\
\left| B\right| &=\left( a_{i}+ka_{j}\right) C_{i,1}+\left(
b_{i}+kb_{j}\right) C_{i,2}+\cdots \\
&=\left( a_{i}C_{i,1}+b_{i}C_{i,2}+\cdots \right) +k\left(
a_{j}C_{i,1}+b_{i}C_{j,2}+\cdots \right)
\end{aligned}$$ $$=\left| 
\begin{array}{cccc}
a_{1} & b_{1} & c_{1} & \cdots \\ 
a_{2} & b_{2} & c_{2} &  \\ 
\vdots &  &  &  \\ 
a_{i} & b_{i} & c_{i} &  \\ 
\vdots &  &  & 
\end{array}
\right| +k\left| 
\begin{array}{cccc}
a_{1} & b_{1} & c_{1} & \cdots \\ 
a_{2} & b_{2} & c_{2} &  \\ 
\vdots &  &  &  \\ 
a_{j} & b_{j} & c_{j} &  \\ 
\vdots &  &  & 
\end{array}
\right| =\left| A\right|$$ since rows $i$ and $j$ in the determinant
$\left| 
\begin{array}{cccc}
a_{1} & b_{1} & c_{1} & \cdots \\ 
a_{2} & b_{2} & c_{2} &  \\ 
\vdots &  &  &  \\ 
a_{j} & b_{j} & c_{j} &  \\ 
\vdots &  &  & 
\end{array}
\right|$ are identical, so it is zero (Corollary \ref{calcdet}, item 4). ◻
:::

::: {.callout-note}
## Remember
The rules are similar to, **but not the same as,**
Gaussian elimination; adding $k$ times row 2 to row 1 is OK if the
result goes in row 1, and row 2 is left unchanged, but if you replace
row 2 by $k$ times row 2 plus row 1, you will change the value of the
determinant by a factor of $k$ (item 3 of Corollary \ref{calcdet} tells us this). A further
difference is that a multiple of a column can be added to another column
(not allowed in Gaussian elimination).
:::

::: {#exm-det6}
Evaluate the determinant $\left| 
\begin{array}{cccc}
1 & 2 & -1 & 3 \\ 
2 & 0 & 1 & 1 \\ 
1 & 3 & 2 & 1 \\ 
2 & 0 & 0 & 1
\end{array}
\right| .$
:::

::: {.Solution}
First expand by the 4th row: $$= -2\times \left| 
\begin{array}{ccc}
2 & -1 & 3 \\ 
0 & 1 & 1 \\ 
3 & 2 & 1
\end{array}
\right| +1\times \left| 
\begin{array}{ccc}
1 & 2 & -1 \\ 
2 & 0 & 1 \\ 
1 & 3 & 2
\end{array}
\right| ,$$

now subtract $c_{3}$ from $c_{2}$ in the 1st , subtract $2\times
c_{3}$ from $c_{1}$ in the 2nd and expand both by their 2nd rows.
$$\begin{aligned}
&=-2\times \left| 
\begin{array}{ccc}
2 & -4 & 3 \\ 
0 & 0 & 1 \\ 
3 & 1 & 1
\end{array}
\right| +1\times \left| 
\begin{array}{ccc}
3 & 2 & -1 \\ 
0 & 0 & 1 \\ 
-3 & 3 & 2
\end{array}
\right| \\
&=-2\times \left( -1\right) \left| 
\begin{array}{cc}
2 & -4 \\ 
3 & 1
\end{array}
\right| +1\times \left( -1\right) \left| 
\begin{array}{cc}
3 & 2 \\ 
-3 & 3
\end{array}
\right| \\
&=-2\times \left( -1\right) \times 14+1\times \left( -1\right) \times 15=13.
\end{aligned}$$
:::

::: {#exm-det7}
Evaluate the determinant 
$$\left| 
\begin{array}{rrrr}
4 & 1 & 3 & -1 \\ 
2 & 0 & 1 & 2 \\ 
1 & -1 & 2 & 5 \\ 
2 & 1 & 3 & 1
\end{array}
\right|$$.
:::

::: {.Solution}
Subtract $r_{4}$ from $r_{1}$; then add $c_{1}$ to $c_{4},$ then expand
about the 1st row:
$$ r_{1}-r_{4}\rightarrow r_{1}: \quad \left| 
\begin{array}{rrrr}
2 & 0 & 0 & -2 \\ 
2 & 0 & 1 & 2 \\ 
1 & -1 & 2 & 5 \\ 
2 & 1 & 3 & 1
\end{array}
\right| ,$$ 
$$c_{4}+c_{1}\rightarrow c_{4}: \quad \left| 
\begin{array}{rrrr}
2 & 0 & 0 & 0 \\ 
2 & 0 & 1 & 4 \\ 
1 & -1 & 2 & 6 \\ 
2 & 1 & 3 & 3
\end{array}
\right| =2\times \left| 
\begin{array}{rrr}
0 & 1 & 4 \\ 
-1 & 2 & 6 \\ 
1 & 3 & 3
\end{array}
\right| $$
add $r_{3}$ to $r_{2}:$ 
$$r_{2}+r_{3}\rightarrow r_{2}: \quad 2\times \left| 
\begin{array}{rrr}
0 & 1 & 4 \\ 
0 & 5 & 9 \\ 
1 & 3 & 3
\end{array}
\right| =2\times 1\times \left| 
\begin{array}{rr}
1 & 4 \\ 
5 & 9
\end{array}
\right| =2\times 1\times \left( -11\right) =-22.$$
:::

::: {.exm-det8}
Show that 
$$D=\left| 
\begin{array}{cccc}
1 & a & a^{2} & b+c+d \\ 
1 & b & b^{2} & c+d+a \\ 
1 & c & c^{2} & d+a+b \\ 
1 & d & d^{2} & a+b+c
\end{array}
\right| =0$$ for all values of $a,b,c,d.$
:::

::: {.exm-det9}
Solve for $x$
$$\left| 
\begin{array}{ccc}
1 & 2 & x \\ 
x & 0 & 3 \\ 
1 & x & 2
\end{array}
\right| =0$$ 
:::

::: {.Corollary}
If $A$ is either lower or upper triangular, then
$\det(A) =a_{1,1}a_{2,2}\cdots a_{n,n}$, is the product of its diagonal
entries.
:::

::: {#exm-det10}
$$\left|\begin{array}{rrr}
1 & 7 & -2 \\
0 & 14 & 32 \\
0 & 0 & -2
\end{array}\right| = 1\times 14\times (-2)=-28$$.

We can see this by expanding down the first column:

$$1\left|\begin{array}{rr} 14 & 32 \\
0 & -2
\end{array}\right|=1(14\times (-2))=-28.$$
:::

::: {.Theorem}
## Product Rule 
For any two matrices $A$ and $B,$
$\det (AB)$ = $\det (A) \det (B)$.
:::

The general proof of this result uses elementary matrices. Although it
is a key result, a proof will not be given (See Poole, p. 268).

Note that $\textrm{det}(A+B)\neq \textrm{det}(A)+\textrm{det}(B)$.

::: {.Corollary}
If $A$ is $n\times n$, we have$,$ by Corollary \ref{calcdet}
$$\begin{aligned}
\det \left( kA\right) &= \det \left( kI \  A\right) \\
&=
\det \left( kI\right)  \det \left( A\right) \\
&= k^{n}
\det \left( A\right) .
\end{aligned}$$
:::

::: {.Corollary}
When $A$ is non-singular (i.e., invertible)
$$\det \left(A^{-1}\right) =\dfrac{1}{\det \left( A\right) }.$$
:::

::: {.Proof}
$1=\textrm{det(I)}=\textrm{det}(AA^{-1})=\textrm{det}(A)\textrm{det}(A^{-1})$. ◻
:::

::: {#exm-det11}
Let $A$ be an $n\times n$ matrix with
$\textrm{det}(A)=5$. Then 
$$\det \left( A^{4}\right)
=5^{4}$$
$$\det \left( A^{-1}\right) =\frac{1}{5},$$ 
$$\det \left( 3A^{2}\right) =3^{n}\times 25$$ .
:::

::: {.Corollary}
The matrix $A$ has an inverse if, and only if,
$\left| A\right| \neq 0.$
:::

::: {.Proof}
First, we show that if the matrix $A$ has an inverse, then
$|A|\neq 0$. If ${\rm A}$ has an inverse then
$|{\rm A}{\rm A^{-1}}| = |{\rm A}||{\rm A^{-1}}| =| I | = 1$ and hence
$|{\rm A}| \neq 0$.

Next, we show the reverse. Assume that $|A|\neq 0$. We want to show that
$A$ has an inverse.

By using elementary row operations, that is by either (i) adding a
multiple of one row to another or (ii) interchanging rows we can reduce
$A$ to upper triangular form---call this $U.$ Operations of type i) do
not affect the value of $\left| A\right|$ while operations of type (ii)
may cause a change of sign. Hence,
$$\left| A\right| =\pm \left| U\right|,$$ and so, in particular
$|A|\neq0$.

$$\begin{aligned}
U&=\left[ 
\begin{array}{cccc}
u_{11} & u_{12} & \cdots & u_{1n} \\ 
0 & u_{22} &  & u_{2n} \\ 
0 & 0 & \ddots &  \\ 
0 & 0 &  & u_{nn}
\end{array}
\right],\\
\left| U\right| &= u_{11}u_{22}\cdots u_{nn}\neq 0,
\end{aligned}$$ so $u_{ij}\neq 0$ for all $i,j=1,2,\dots,n$. Hence $A$
has $n$ pivots and is invertible. ◻
:::

::: {.Corollary}
If $A$ is a square matrix, the system
$A\mathbf{x=0}$ has non-trivial solutions if, and only if,
$\left| A\right| =0$ (so $A$ is a singular matrix).
:::

::: {.callout-note}
## Note: 
Various authors define non-singular matrices to be either

- invertible matrices

- matrices $A$ for which $\det(A)\neq 0$.

- matrices for which $A\mathbf{x}=\mathbf{0}$ has only the trivial
  (zero) solution.

The above theorem shows that they are all equivalent definitions.
:::


## The Adjoint Matrix

::: {.Definition}
The transpose of the matrix of cofactors of ${\rm A}$ is
called the *adjugate* or *adjoint* of ${\rm A}$ and denoted by
$\rm{adj}({\rm A}) =(\text{Cofactors})^{T}$.
:::

::: {.Theorem}
## Inverse and Adjoint
If $\det({\rm A}) \neq 0$ then
$${\rm A}^{-1} =\frac{1}{\det({\rm A})} \rm{adj}({\rm A}).$$
:::

::: {.Proof}
Let ${\rm C}$ be the matrix of cofactors of ${\rm A}$.
$$\begin{aligned}
 ({\rm A} \  \rm{adj}({\rm A}))_{ij} &= \sum_{k=1}^{n} a_{ik} ({\rm C}^{T})_{kj} =  \sum_{k=1}^{n} a_{ik} {\rm C}_{jk} \\
 &= \left\{ 
\begin{array}{cc}
0 & i \neq j \\ 
\det(\rm{A}) & i=j
\end{array}
\right. \\
\Rightarrow {\rm A} \  \rm{adj}({\rm A}) &= \det(\rm{A}) {\rm I} 
\end{aligned}$$ Here, the result for $i\neq j$ is obtained from the fact
that $\sum_{k=1}^{n} a_{ik} {\rm C}_{jk}$ is the expansion of the
determinant of a matrix with two identical rows. For the case $i=j$,
however, this is exactly the definition of the expansion of a
determinant along row $i$ of ${\rm A}$. So $$\begin{aligned}
&& A\textrm{adj}(A)=\det(A)I \\
&\Leftrightarrow& \frac{A \textrm{adj}(A)}{\det(A)}=I.
\end{aligned}$$ Multiplying $A^{-1}$ from the left gives
$$\frac{1}{\det(A)} \textrm{adj}(A)=A^{-1}.$$ ◻
:::

::: {#exm-adj1}
Find the adjoint of the matrix
$${\rm A}=\left[
\begin{array}{ccc}
1 & -1 & 2\\
3 & 2 & -1\\
2 & -1 & 2\\
\end{array}
\right]$$
:::

::: {.Solution}
\(i\) Matrix of minors is 
$$\left[
\begin{array}{rrr}
3 & 8 & -7\\
0 & -2 & 1\\
-3 & -7 & 5
\end{array}
\right].$$ 
(ii) The matrix of cofactors is 
$$\left[
\begin{array}{rrr}
3 & -8 & -7\\
0 & -2 & -1\\
-3 & 7 & 5
\end{array}
\right].$$ 
(iii) Adjoint is 
$${\rm adj}({\rm A}) = \left[
\begin{array}{rrr}
3 & 0 & -3\\
-8 & -2 & 7\\
-7 & -1 & 5
\end{array}
\right].$$

Notice that
$${\rm A} \,  {\rm adj}({\rm A}) = \left[
\begin{array}{rrr}
1 & -1 & 2\\
3 & 2 & -1\\
2 & -1 & 2\\
\end{array}
\right]
\left[
\begin{array}{rrr}
3 & 0 & -3\\
-8 & -2 & 7\\
-7 & -1 & 5
\end{array}
\right]$$ $$= \left[
\begin{array}{rrr}
-3 & 0 & 0\\
0  & -3 & 0\\
0 & 0 & -3
\end{array}
\right] = -3 I = det(A) I.$$
:::

::: {#exm-adj2}
Use the adjoint matrix to find the inverse of the matrix
$A=\left(\begin{array}{rrr}1 & -1 & 2 \\ 3 & 2 & -1 \\ 2 & -1 & 2\end{array}\right)$
in the previous example.
:::

::: {.Solution}
The determinant of the matrix $A$ is 
$$\begin{aligned}
&&1\left|\begin{array}{rr}2 & -1 \\ -1 & 2\end{array}\right|+
1\left|\begin{array}{rr}3 & -1 \\ 2 & 2\end{array}\right|
-2\left|\begin{array}{rr}3 & 2 \\ 2 & -1\end{array}\right| \\
&= (4-1)+(6+2)+2(-3-4)\\
&= 3+8 -14\\
&=-3.
\end{aligned}$$ Thus, the inverse is
$$A^{-1}=\frac{-1}{3}\left(\begin{array}{rrr}
3 & 0 & -3 \\
-8 & -2 & 7 \\
-7 & -1 & 5
\end{array}\right).$$
:::

::: {#exm-adj3}
Find the inverse of $$A=\left(\begin{array}{rrr}
2 & 3 & 4 \\
5 & 6 & 7 \\
8 & 9 & 1
\end{array}\right).$$
:::

::: {.Solution}
$$\begin{aligned}
\det(A) &= 2\left|\begin{array}{rr}
6 & 7 \\
9 & 1
\end{array}\right|
-3\left|\begin{array}{rr}
5 & 7 \\
8 & 1
\end{array}\right|
+4\left|\begin{array}{rr}
5 & 6 \\
8 & 9
\end{array}\right| \\
&= 2(6-63)-3(5-56)+4(45-48) \\
&= 2(-57)-3(-51)+4(-3) \\
&= -114+153-12 \\
&= 27.
\end{aligned}$$

$$\begin{aligned}
A^{-1} &= \frac{1}{27}
\left(\begin{array}{rrr}
-57 & 33 & -3 \\
51 & -30 & 6 \\
-3 & 6 & -3
\end{array}\right) \\
&= \frac{1}{9}\left(\begin{array}{rrr}
-19 & 11 & -1 \\
17 & -10 & 2 \\
-1 & 2 & -1
\end{array}\right).
\end{aligned}$$
:::

::: {#exm-adj4}
In the $2\times 2$ case, if 
$$\begin{aligned}
A&=\left[ 
\begin{array}{cc}
a & b \\ 
c & d
\end{array}
\right] \ \Rightarrow  \  {\rm adj}({\rm A}) = \left[\begin{array}{rr}
d & -b \\ 
-c & a
\end{array}
\right]  \\
 \Rightarrow A^{-1} &= \frac{1}{ad-bc}\left[ 
\begin{array}{rr}
d & -b \\ 
-c & a
\end{array}
\right].  
\end{aligned}$$
:::

